import Vue from 'vue';
import ConfirmDialog from './ConfirmDialog';
import EditDeleteGroup from './EditDeleteGroup';
import Lov from './Lov';
import LovDialog from "./LovDialog";
import SimpleTable from './SimpleTable';
import RequestText from './RequestText';
import ResponseText from './ResponseText';
import FieldEditor from './FieldEditor';
import IconSelector from "./IconSelector";
import ColorSelector from "./ColorSelector";
import ModelImport from "./ModelImport";
import FormField from "./FormField";
import SimpleForm from "./SimpleForm";
import IconSelectorBtn from "./IconSelectorBtn";
import ColorSelectorBtn from "./ColorSelectorBtn";
import FormSelectorField from "./FormSelectorField";
import FormTextAreaField from "./FormTextAreaField";
import DialogWrapper from "./DialogWrapper";
import LinkText from "./LinkText";
import FormFunctionField from "./FormFunctionField";
import FormAutoComplete from "./FormAutoComplete";
import VC from './VC';
import FormDateSelector from "./FormDateSelector";
import PageDataTable from "./PageDataTable";

Vue.component('v-confirm-dialog', ConfirmDialog);
Vue.component('v-edit-delete-group', EditDeleteGroup);
Vue.component('v-lov', Lov);
Vue.component('v-vc', VC);
Vue.component('v-lov-dialog', LovDialog);
Vue.component('v-simple-table', SimpleTable);
Vue.component('v-request-text', RequestText);
Vue.component('v-response-text', ResponseText);
Vue.component('v-field-editor', FieldEditor);
Vue.component('v-icon-selector', IconSelector);
Vue.component('v-color-selector', ColorSelector);
Vue.component('v-model-import', ModelImport);
Vue.component('v-form-field', FormField);
Vue.component('v-form-date-selector', FormDateSelector);
Vue.component('v-form-selector', FormSelectorField);
Vue.component('v-form-textarea', FormTextAreaField);
Vue.component('v-form-autocomplete', FormAutoComplete);
Vue.component('v-dialog-wrapper', DialogWrapper);
Vue.component('v-simple-form', SimpleForm);
Vue.component('v-icon-selector-btn', IconSelectorBtn);
Vue.component('v-color-selector-btn', ColorSelectorBtn);
Vue.component('v-link-text', LinkText);
Vue.component('v-function-editor', FormFunctionField);
Vue.component('v-page-data-table', PageDataTable);
